# Generated by Django 2.2.1 on 2019-11-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='userid',
        ),
    ]
