# Generated by Django 2.2.1 on 2019-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_cloth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('designer', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Cloth',
        ),
    ]
