# Generated by Django 2.2.1 on 2019-11-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_review_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
