# Generated by Django 2.2.1 on 2019-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20191102_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('designer', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
