# Generated by Django 2.2.1 on 2019-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20191103_0137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommend_List',
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(),
        ),
    ]
